name: PR Check

on:
  pull_request:
    branches: [master, api-overhaul]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            json:
              - 'frontend/**/*.json'
            scss:
              - 'frontend/**/*.scss'
            ts:
              - 'frontend/**/*.js'
              - 'frontend/**/*.ts'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm run install:all

      # - name: Run webpack
      #   run: npm run build:live

      - name: Lint and validate JSON
        if: steps.filter.outputs.json == 'true'
        run: npm run pr-check-json

      - name: Lint and compile SCSS
        if: steps.filter.outputs.scss == 'true'
        run: npm run pr-check-scss

      - name: Lint source code and run webpack
        if: steps.filter.outputs.scss == 'true'
        run: npm run pr-check-ts
