name: Publish Docker image

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Backend extract metadata (tags, labels)
        id: bemeta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: fehmer/mt-backend
          tags: |
            type=semver,pattern={{version}}

      - name: Backend build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: fehmer/mt-backend:latest,${{ steps.bemeta.outputs.tags }}
          labels: ${{ steps.bemeta.outputs.labels }}
          
      - name: Frontend extract metadata (tags, labels)
        id: femeta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: fehmer/mt-frontend
          tags: |
            type=semver,pattern={{version}}

      - name: Frontend build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: fehmer/mt-frontend:latest,${{ steps.bemeta.outputs.tags }}
          labels: ${{ steps.bemeta.outputs.labels }}